### ISSUE TITLE
Remove derived states from React components

### ISSUE THREAD

**Issue by asktree** [sdspikes/reciprocity2#43]
Example: The component `Profile` has props `profile_items`, `item_data`, and `categories`, all of which are forwarded to the state. Because these variables are controlled both by the component and its parents, I can't know when they can be safely changed. The parents seem to be written in Ruby so I don't really know how to decipher this information on my own, either.

Suggestion: Either allow `Profile` to initialize and control these variables on its own, or not at all.

Read more: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by asktree** [comment]
If it is the case that the parent element will never rerender, then it would be acceptable to explain that in a comment.

**Comment by sdspikes** [comment]
This data comes from the database. I am not sure how Profile would "initialize" these on it's own, unless it did an ajax call, but we've already done the work of getting the data on the ruby side so that seems redundant?  The main objection I see in that post is "But if our component’s parent rerenders" -- but the ruby view will only re-render if you reload the page.  The props will not change.  I may well be missing something, though.

It's possible that the component should not be passed any props and should instead get everything through ajax calls, which would require major rewrites of the whole app.  I'd prefer to avoid that unless absolutely necessary.
